"use client";

import { useEffect, useState } from "react";

function getSupportedMimeTypes() {
   const mimeTypes = [
      "video/webm;codecs=vp9",
      "video/webm;codecs:vp9",
      "video/webm;codecs=VP9",
      "video/webm;codecs:VP9",
      "video/webm",
      "video/webm;codecs=vp9.0",
      "video/webm;codecs:vp9.0",
      "video/webm;codecs=VP9.0",
      "video/webm;codecs:VP9.0",
      "video/webm",
      "video/webm;codecs=vp8",
      "video/webm;codecs:vp8",
      "video/webm;codecs=VP8",
      "video/webm;codecs:VP8",
      "video/webm",
      "video/webm;codecs=vp8.0",
      "video/webm;codecs:vp8.0",
      "video/webm;codecs=VP8.0",
      "video/webm;codecs:VP8.0",
      "video/webm",
      "video/webm;codecs=avc1",
      "video/webm;codecs:avc1",
      "video/webm;codecs=AVC1",
      "video/webm;codecs:AVC1",
      "video/webm",
      "video/webm;codecs=av1",
      "video/webm;codecs:av1",
      "video/webm;codecs=AV1",
      "video/webm;codecs:AV1",
      "video/webm",
      "video/webm;codecs=h265",
      "video/webm;codecs:h265",
      "video/webm;codecs=H265",
      "video/webm;codecs:H265",
      "video/webm",
      "video/webm;codecs=h.265",
      "video/webm;codecs:h.265",
      "video/webm;codecs=H.265",
      "video/webm;codecs:H.265",
      "video/webm",
      "video/webm;codecs=h264",
      "video/webm;codecs:h264",
      "video/webm;codecs=H264",
      "video/webm;codecs:H264",
      "video/webm",
      "video/webm;codecs=h.264",
      "video/webm;codecs:h.264",
      "video/webm;codecs=H.264",
      "video/webm;codecs:H.264",
      "video/webm",
      "video/webm;codecs=opus",
      "video/webm;codecs:opus",
      "video/webm;codecs=OPUS",
      "video/webm;codecs:OPUS",
      "video/webm",
      "video/ogg;codecs=vp9",
      "video/ogg;codecs:vp9",
      "video/ogg;codecs=VP9",
      "video/ogg;codecs:VP9",
      "video/ogg",
      "video/ogg;codecs=vp9.0",
      "video/ogg;codecs:vp9.0",
      "video/ogg;codecs=VP9.0",
      "video/ogg;codecs:VP9.0",
      "video/ogg",
      "video/ogg;codecs=vp8",
      "video/ogg;codecs:vp8",
      "video/ogg;codecs=VP8",
      "video/ogg;codecs:VP8",
      "video/ogg",
      "video/ogg;codecs=vp8.0",
      "video/ogg;codecs:vp8.0",
      "video/ogg;codecs=VP8.0",
      "video/ogg;codecs:VP8.0",
      "video/ogg",
      "video/ogg;codecs=avc1",
      "video/ogg;codecs:avc1",
      "video/ogg;codecs=AVC1",
      "video/ogg;codecs:AVC1",
      "video/ogg",
      "video/ogg;codecs=av1",
      "video/ogg;codecs:av1",
      "video/ogg;codecs=AV1",
      "video/ogg;codecs:AV1",
      "video/ogg",
      "video/ogg;codecs=h265",
      "video/ogg;codecs:h265",
      "video/ogg;codecs=H265",
      "video/ogg;codecs:H265",
      "video/ogg",
      "video/ogg;codecs=h.265",
      "video/ogg;codecs:h.265",
      "video/ogg;codecs=H.265",
      "video/ogg;codecs:H.265",
      "video/ogg",
      "video/ogg;codecs=h264",
      "video/ogg;codecs:h264",
      "video/ogg;codecs=H264",
      "video/ogg;codecs:H264",
      "video/ogg",
      "video/ogg;codecs=h.264",
      "video/ogg;codecs:h.264",
      "video/ogg;codecs=H.264",
      "video/ogg;codecs:H.264",
      "video/ogg",
      "video/ogg;codecs=opus",
      "video/ogg;codecs:opus",
      "video/ogg;codecs=OPUS",
      "video/ogg;codecs:OPUS",
      "video/ogg",
      "video/mp4;codecs=vp9",
      "video/mp4;codecs:vp9",
      "video/mp4;codecs=VP9",
      "video/mp4;codecs:VP9",
      "video/mp4",
      "video/mp4;codecs=vp9.0",
      "video/mp4;codecs:vp9.0",
      "video/mp4;codecs=VP9.0",
      "video/mp4;codecs:VP9.0",
      "video/mp4",
      "video/mp4;codecs=vp8",
      "video/mp4;codecs:vp8",
      "video/mp4;codecs=VP8",
      "video/mp4;codecs:VP8",
      "video/mp4",
      "video/mp4;codecs=vp8.0",
      "video/mp4;codecs:vp8.0",
      "video/mp4;codecs=VP8.0",
      "video/mp4;codecs:VP8.0",
      "video/mp4",
      "video/mp4;codecs=avc1",
      "video/mp4;codecs:avc1",
      "video/mp4;codecs=AVC1",
      "video/mp4;codecs:AVC1",
      "video/mp4",
      "video/mp4;codecs=av1",
      "video/mp4;codecs:av1",
      "video/mp4;codecs=AV1",
      "video/mp4;codecs:AV1",
      "video/mp4",
      "video/mp4;codecs=h265",
      "video/mp4;codecs:h265",
      "video/mp4;codecs=H265",
      "video/mp4;codecs:H265",
      "video/mp4",
      "video/mp4;codecs=h.265",
      "video/mp4;codecs:h.265",
      "video/mp4;codecs=H.265",
      "video/mp4;codecs:H.265",
      "video/mp4",
      "video/mp4;codecs=h264",
      "video/mp4;codecs:h264",
      "video/mp4;codecs=H264",
      "video/mp4;codecs:H264",
      "video/mp4",
      "video/mp4;codecs=h.264",
      "video/mp4;codecs:h.264",
      "video/mp4;codecs=H.264",
      "video/mp4;codecs:H.264",
      "video/mp4",
      "video/mp4;codecs=opus",
      "video/mp4;codecs:opus",
      "video/mp4;codecs=OPUS",
      "video/mp4;codecs:OPUS",
      "video/mp4",
      "video/x-matroska;codecs=vp9",
      "video/x-matroska;codecs:vp9",
      "video/x-matroska;codecs=VP9",
      "video/x-matroska;codecs:VP9",
      "video/x-matroska",
      "video/x-matroska;codecs=vp9.0",
      "video/x-matroska;codecs:vp9.0",
      "video/x-matroska;codecs=VP9.0",
      "video/x-matroska;codecs:VP9.0",
      "video/x-matroska",
      "video/x-matroska;codecs=vp8",
      "video/x-matroska;codecs:vp8",
      "video/x-matroska;codecs=VP8",
      "video/x-matroska;codecs:VP8",
      "video/x-matroska",
      "video/x-matroska;codecs=vp8.0",
      "video/x-matroska;codecs:vp8.0",
      "video/x-matroska;codecs=VP8.0",
      "video/x-matroska;codecs:VP8.0",
      "video/x-matroska",
      "video/x-matroska;codecs=avc1",
      "video/x-matroska;codecs:avc1",
      "video/x-matroska;codecs=AVC1",
      "video/x-matroska;codecs:AVC1",
      "video/x-matroska",
      "video/x-matroska;codecs=av1",
      "video/x-matroska;codecs:av1",
      "video/x-matroska;codecs=AV1",
      "video/x-matroska;codecs:AV1",
      "video/x-matroska",
      "video/x-matroska;codecs=h265",
      "video/x-matroska;codecs:h265",
      "video/x-matroska;codecs=H265",
      "video/x-matroska;codecs:H265",
      "video/x-matroska",
      "video/x-matroska;codecs=h.265",
      "video/x-matroska;codecs:h.265",
      "video/x-matroska;codecs=H.265",
      "video/x-matroska;codecs:H.265",
      "video/x-matroska",
      "video/x-matroska;codecs=h264",
      "video/x-matroska;codecs:h264",
      "video/x-matroska;codecs=H264",
      "video/x-matroska;codecs:H264",
      "video/x-matroska",
      "video/x-matroska;codecs=h.264",
      "video/x-matroska;codecs:h.264",
      "video/x-matroska;codecs=H.264",
      "video/x-matroska;codecs:H.264",
      "video/x-matroska",
      "video/x-matroska;codecs=opus",
      "video/x-matroska;codecs:opus",
      "video/x-matroska;codecs=OPUS",
      "video/x-matroska;codecs:OPUS",
      "video/x-matroska",
   ];

   const supportedMimeTypes = mimeTypes.filter((mimeType) =>
      MediaRecorder.isTypeSupported(mimeType),
   );
   return supportedMimeTypes;
}

function VideoSupport() {
   const [supportedMimeTypes, setSupportedMimeTypes] = useState<string[]>([]);

   useEffect(() => {
      setSupportedMimeTypes(getSupportedMimeTypes());
   }, []);

   return (
      <div className="flex flex-col justify-center items-center w-screen h-screen">
         <h1 className="mb-2 font-semibold text-center text-xl">
            Formatos soportados
         </h1>
         <ul className="h-96 overflow-y-auto">
            {supportedMimeTypes.map((mimeType) => (
               <li key={mimeType}>{mimeType}</li>
            ))}
         </ul>
      </div>
   );
}

export default VideoSupport;
